[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sjl/gundo.vim'
if = "has('python')"

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# filetypes
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'nikolavp/sparql.vim'
on_ft = 'sparql'

[[plugins]]
repo = 'niklasl/vim-rdf'
